# This is a basic workflow to help you get started with Actions
name: OpenWRTBuilder

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REPOSITORY_URL: https://github.com/coolsnowwolf/lede
  REPOSITORY_BRANCH: master
  REPOSITORY_COMMIT_ID: b1b6cd41bb9d4f63ab2870177cbaf5031d41aea5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 初始化系统
      - name: Initialization
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      # 克隆源码
      - name: Clone Repository
        run: |
          git clone $REPOSITORY_URL -b $REPOSITORY_BRANCH OpenWRT
          cd OpenWRT
          git checkout $REPOSITORY_COMMIT_ID
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 加载配置
      - name: Load Config
        run: |
          rm -rf OpenWRT/.config
          mv .config OpenWRT/.config

      # 下载依赖
      - name: Download Package
        run: |
          cd OpenWRT
          make defconfig
          make download -j8

      # 编译固件
      - name: Compile Firmware
        run: |
          cd OpenWRT
          make V=s -j1

      # 上传固件
      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: firmware
          path: OpenWRT/bin
